{% set name = "looptools" %}
{% set version = "2.16" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://feynarts.de/looptools/LoopTools-{{ version }}.tar.gz
  sha256: 4113467575db3a14405d62d9e516b3b90410b73ea8d20c8eb8d70a30fc5cc9cb

build:
  number: 1

outputs:
  - name: {{ name }}-static

    build:
      skip: true  # [win]
      ignore_run_exports_from:
        # Need cxx compiler to build but only c compiler to run
        - {{ compiler('cxx') }}
      script:
        # FIXME: Avoid error from trying to create directories that exist
        - sed -i 's/mkdir /mkdir -p /g' makefile.in
        # FIXME: Ensure correct OS-version of strip is used for cross-compile builds.
        - sed -i "s|strip |$STRIP |g" makefile.in
        - ./configure --help
        # FIXME: Author has disabled builds with dynamic linking
        # c.f. https://github.com/hep-packaging-coordination/packaging-hep-simulation-stack/issues/4#issuecomment-2489198926
        # FIXME: Set --64 flag to avoid erroring on macOS arm64 when checking for 32-bit support
        # - ./configure --prefix=$PREFIX --64 --dynamic
        - ./configure --prefix=$PREFIX --64
        - make
        - make install
        # conda just uses $PREFIX/lib (x86 and ppc64le will try to use $PREFIX/lib64)
        - mv $PREFIX/lib64/libooptools.a $PREFIX/lib/libooptools.a  # [linux and not aarch64]
        - rm -rf build

    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - make
        - sed
        - gawk

    test:
      files:
        - examples/
      requires:
        - {{ compiler('cxx') }}
        - gfortran
      commands:
        - test ! -f $PREFIX/lib64/libooptools.a  # [linux]
        - test -f $PREFIX/lib/libooptools.a
        - test -f $PREFIX/include/looptools.h
        - test -f $PREFIX/include/clooptools.h
        - test -f $PREFIX/bin/lt
        - test -f $PREFIX/bin/fcc
        - test -f $PREFIX/bin/f++

        - fcc --help
        - f++ --help

        - cd examples
        - $CXX example01.cpp -o example01 $CXXFLAGS $LDFLAGS -looptools -lgfortran
        - ./example01

about:
  home: https://feynarts.de/looptools/
  summary: 'LoopTools: A package for evaluation of scalar and tensor one-loop integrals'
  description: |
    LoopTools is a package for evaluation of scalar and tensor one-loop integrals
    based on the FF package by G.J. van Oldenborgh. It features an easy Fortran,
    C++, and Mathematica interface to the scalar one-loop functions of FF and
    in addition provides the 2-, 3-, and 4-point tensor coefficient functions.

    The [publication](https://inspirehep.net/literature/474106) associated with
    LoopTools is: T. Hahn, M. Pérez-Victoria. Automated one-loop calculations
    in four and D dimensions, _Comput. Phys. Commun._ 118 (1999) 153.
    DOI: [10.1016/S0010-4655(98)00173-8](https://doi.org/10.1016/S0010-4655(98)00173-8)
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - matthewfeickert
