{% set name = "looptools" %}
{% set version = "2.16" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://feynarts.de/looptools/LoopTools-{{ version }}.tar.gz
  sha256: 4113467575db3a14405d62d9e516b3b90410b73ea8d20c8eb8d70a30fc5cc9cb

build:
  number: 1

outputs:
  - name: {{ name }}-static

    build:
      skip: true  # [win]
      script:
        # FIXME: Avoid error from trying to create directories that exist
        - sed -i 's/mkdir /mkdir -p /g' makefile.in
        # FIXME: Ensure correct OS-version of strip is used for cross-compilation
        - sed -i "s|strip |$STRIP |g" makefile.in

        # FIXME:
        # In configure, 'findprog' sets values of CONF_CC and CONF_CXX. Override
        # these in src/makefile to use PREFIX instead of BUILD_PREFIX, so that
        # conda-build can patch the PREFIX path.
        - export _VAR='export CONF_CC=$(echo "$CONF_CC" | sed "s|$BUILD_PREFIX|$PREFIX|g") \&\& export CONF_CXX=$(echo "$CONF_CXX" | sed "s|$BUILD_PREFIX|$PREFIX|g")'
        - sed -i 's#sed -e#_ZZZ \&\& sed -e#g' src/makefile
        - sed -i 's#_ZZZ#'"$_VAR"'#g' src/makefile
        - unset _VAR

        # FIXME: Avoid FLDFLAGS that use $BUILD_PREFIX gettting added to LDFLAGS
        - sed -i 's/$LDFLAGS $CONF_LDFLAGS $FLDFLAGS/$LDFLAGS $CONF_LDFLAGS -lgfortran/g' configure

        # Get an updated config.sub and config.guess for cross-compilation
        - cp $BUILD_PREFIX/share/gnuconfig/config.* .
        - ./configure --help
        # FIXME: Author has disabled builds with dynamic linking
        # c.f. https://github.com/hep-packaging-coordination/packaging-hep-simulation-stack/issues/4#issuecomment-2489198926
        # - ./configure --prefix=$PREFIX --dynamic
        - ./configure --prefix=$PREFIX
        - make
        - make install
        # FIXME: Shell script has hard coded $BUILD_PREFIX but conda-build
        # doesn't patch that out like it does for $PREFIX. So switch
        # $BUILD_PREFIX to $PREFIX for conda-build to patch everything as if it
        # was $PREFIX.
        # Note this is bad as you're now also hard coding in specific versions
        # of tools into paths, which, in the future, will be different at
        # install time than they were at build time.
        - sed -i "s|$BUILD_PREFIX|$PREFIX|g" $PREFIX/bin/fcc
        # conda just uses $PREFIX/lib (x86 and ppc64le will try to use $PREFIX/lib64)
        - mv $PREFIX/lib64/libooptools.a $PREFIX/lib/libooptools.a  # [linux and not aarch64]
        - rm -rf build

    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - make
        - pkg-config
        - gnuconfig
        - sed
        - gawk

    test:
      files:
        - examples/
      requires:
        - {{ compiler('cxx') }}
        - gfortran
      commands:
        - test ! -f $PREFIX/lib64/libooptools.a  # [linux]
        - test -f $PREFIX/lib/libooptools.a
        - test -f $PREFIX/include/looptools.h
        - test -f $PREFIX/include/clooptools.h
        - test -f $PREFIX/bin/lt
        - test -f $PREFIX/bin/fcc
        - test -f $PREFIX/bin/f++

        # lt --help has exit code 1, so run simple program instead
        - lt 1
        # DEBUG
        - cat $(command -v fcc)
        - fcc --help
        - f++ --help

        - cd examples
        - $CXX example01.cpp -o example01 $CXXFLAGS $LDFLAGS -looptools -lgfortran
        - ./example01

about:
  home: https://feynarts.de/looptools/
  summary: 'LoopTools: A package for evaluation of scalar and tensor one-loop integrals'
  description: |
    LoopTools is a package for evaluation of scalar and tensor one-loop integrals
    based on the FF package by G.J. van Oldenborgh. It features an easy Fortran,
    C++, and Mathematica interface to the scalar one-loop functions of FF and
    in addition provides the 2-, 3-, and 4-point tensor coefficient functions.

    The [publication](https://inspirehep.net/literature/474106) associated with
    LoopTools is: T. Hahn, M. Pérez-Victoria. Automated one-loop calculations
    in four and D dimensions, _Comput. Phys. Commun._ 118 (1999) 153.
    DOI: [10.1016/S0010-4655(98)00173-8](https://doi.org/10.1016/S0010-4655(98)00173-8)
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - matthewfeickert
